### ISSUE TITLE
Application needs to Encrypt and Decrypt stored passwords

### ISSUE THREAD

**Issue by rpastor** [rpastor/passkeeper#2]
The application needs a way to interact with the Storage provider. The Storage provider will provide access to stored passwords for retrieval and modification. 

Since this class represents the main functionality of the application, let's call this class *PassKeeper*.

# Requirements

There needs to be a class which is responsible for interacting with the Storage provider. This class must ensure that all passwords provided to the storage are encrypted and passwords retrieved are decrypted. In addition, this class must handle the following exception cases:

* The provided unlock secret does not match the stored value
* The service name cannot be added because it already exists
* The service name cannot be deleted because it does not exist
* Unable to retrieve password because the service name does not exist
* Unable to decrypt password due to an unexpected error
* Unable to update storage due to an unexpected error

## Methods

```csharp
string[[] GetPasswordList();

string GetPassword(string serviceName, string rawUnlockSecret);

void AddPassword(string serviceName, string rawServicePassword);

void UpdatePassword(string serviceName, string rawServicePassword, string rawUnlockSecret);

void DeletePassword(string serviceName, string rawUnlockSecret);
```

## Constructor

The constructor for this class will take an IStorageProvider, which it will use to interact with the Storage provider without needing to know the details of how storage is done.

```csharp
PassKeeper(IStorageProvider storage);
```

**Comment by happymonk** [comment]
I'm going to try using [BCrypt](https://bcrypt.codeplex.com/SourceControl/latest#BCrypt.Net/BCrypt.cs) for encryption.

**Comment by rpastor** [comment]
BCrypt is only for password hashing. A Hash is a one-way encryption of a password, so it is masked when stored in a database or file (no one can read the password). There is no way to get back the original password. If someone provides a password, BCrypt can hash it and verify that it matches the stored version.

What we need is something that offers an Encrypt/Decrypt option. There are classes in the base .net core library to do this. I will find a link.

**Comment by rpastor** [comment]
You could look at this example: http://stackoverflow.com/questions/38795103/encrypt-string-in-net-core. For our purposes, we could just use a non-random, hard coded, key (otherwise we need to store the key to ensure we can decrypt it).
