### ISSUE TITLE
Application needs a command-line interface

### ISSUE THREAD

**Issue by rpastor** [rpastor/passkeeper#3]
For easy testing initially, we should be able to invoke the application functionality using a console application.

# Requirements

The console application should support the following cases:

List all stored service names, each on a new line
```
pkpr list
```

Add a new password
```
pkpr add -s "github" -p "my-github-password"
```

Retrieve a password
```
pkpr get -s "github" -u "my-unlock-secret"
```

Update a password
```
pkpr update -s "github" -p "my-new-github-password" -u "my-unlock-secret"
```

Delete a password
```
pkpr delete -s "github" -u "my-unlock-secret"
```

**Comment by happymonk** [comment]
Is the correct behavior for `Delete` to remove both the service and password, or only the password?

**Comment by rpastor** [comment]
I would say it should remove both. If you think about "list" for example, you would assume that you can do a "get" on any item in the list.
